### ISSUE TITLE
Make changes to the registration form

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#104]
V.0.0.7 (preview)
- [x] Make child first name non-required field - user should be able to save the registration form even if the child's first name is not provided. See the screenshot below on how it looks in old ZEIR. 
![image](https://user-images.githubusercontent.com/58034047/111791272-1e6f7f80-88d4-11eb-81d5-2db73e7e3cc7.png)
- [x] Make the facility of the user the child's home facility - OpenSRP should capture the facility the child is registered as the child's home facility. This should be automatically updated on the app during registration. Currently on preview- this is pulling so many facilities. 
Note: This functionality exists on Tunisia. 
![image](https://user-images.githubusercontent.com/58034047/111787756-5eccfe80-88d0-11eb-898f-a66c7be13090.png)
- [x] The child's zone is missing - this was in version 0.0.7
![image](https://user-images.githubusercontent.com/58034047/111790368-2bd83a00-88d3-11eb-86c5-93406cdab66d.png)
- [x] The location hierarchy on the question - which health facility the child was born in is off - it is pulling so any locations.  Response on the **Place of birth** question for the child should: 1) Pull the location hierarchy only for the facility 2) Should contain the ''Other'' option and allow the user to add another location. See the snapshot below of how it should work. 
https://user-images.githubusercontent.com/58034047/111792903-c89bd700-88d5-11eb-8ef3-df0598b87985.mp4

**Comment by ellykits** [comment]
@AnnieMungai. Why do we need 'Other' option for the zone, when the zones displayed are only for those that are below the Health Facility?  The facilities loaded in the form are also based on the District level obtained from the location hierarchy of the logged in Health Worker - which may have more than one Health Facility.

**Comment by ellykits** [comment]
There maybe an issue with location assignment for preview the server however the functionality work as expected on for the debug apk. As stated earlier the locations added to the dropdown are obtained from the users location hierarchy.

**Comment by AnnieMungai** [comment]
> @AnnieMungai. Why do we need 'Other' option for the zone, when the zones displayed are only for those that are below the Health Facility? The facilities loaded in the form are also based on the District level obtained from the location hierarchy of the logged in Health Worker - which may have more than one Health Facility.

@ellykits if you look at the clip shared, the other is not under the child's zone, it is under the facility. See clip attached above.

**Comment by AnnieMungai** [comment]
v.0.0.8-preview
Looks good!
