### ISSUE TITLE
Sync fails the after first log in

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#106]
V.0.0.8- preview (Demo1)

Sync fails when you log in the first time on the app. This is the error that the users are getting:
![image](https://user-images.githubusercontent.com/58034047/112282179-ec756900-8c97-11eb-8008-b4236610846d.png)

**Comment by ellykits** [comment]
Did we have the LocationService view populated @AnnieMungai? The locations are used for sync. I think this could be related to the bug where the view is not populated with the locations. Workaround is relogin until we have a fix for that.

**Comment by AnnieMungai** [comment]
@ellykits unfortunately I did not check that.

**Comment by AnnieMungai** [comment]
v.0.0.9 
I would say this was resolved and is not an issue anymore.
