### ISSUE TITLE
Amend the phone number format

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#11]
- [x] Update the phone number format {Mother_Guardian_Number} to 0XXXXXXXXX. (Initially, it was in the format Number must begin with 095, 096, or 097)
- [x] The number to start with a zero and limit to 10digits. 

See the updated requirement on t[his data dictionary](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=0) - row 18 (highlighted in green).

**Comment by cafootitt** [comment]
@AnnieMungai Since we have new engineers on this project, please link to the data dictionary, explaining in which form this field can be found. It would be helpful to list out what the current constraint logic on the field is as well.

**Comment by AnnieMungai** [comment]
v0.0.1-r2

Looks great!
