### ISSUE TITLE
v.0.0.8-r3 - preview QA

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#115]
User: biduser
- [x] Daily tallies missing data from 2017 Nov - 2021 (Jan &Feb).
![image](https://user-images.githubusercontent.com/58034047/112771698-c6ecb480-9035-11eb-8a72-5b550456d55a.png)
- [x] HIA2 Reports- same thing as above - missing reports. 
![image](https://user-images.githubusercontent.com/58034047/112771833-6dd15080-9036-11eb-91e2-80401896422d.png)
- [x] HIA2 Sent reports missing completely (are there no sent reports ever sent by this user?)
- [x] Inconsistent sync results; sync says complete but still continues. Also when the device sleeps, sync pauses.  (@ellykits is there a way to allow the device to run until the sync is completed? Maybe implement wake_lock when sync is happening?)
- [ ] ZEIR coverage report - not picking target number, thus all reports are showing 0%. 
![image](https://user-images.githubusercontent.com/58034047/112771753-16cb7b80-9036-11eb-8d27-3e5c21778719.png)
- [ ] All coverage reports showing only 2 years  - we have data that goes beyond this. 
![image](https://user-images.githubusercontent.com/58034047/112772142-edabea80-9037-11eb-9ebb-0bc3b73a2893.png)

**Comment by hamza-vd** [comment]
@AnnieMungai @ellykits 

In reference to the last point:

> “All coverage reports showing only 2 years - we have data that goes beyond this.”

Upon my investigation, I found that only vaccines which are given <= 12 months ago (or 24 months in case of MR2) are considered valid (due to restriction of child age <= 12 months), which is why it always shows data for the last two years. All the vaccines given 13 or more months ago are never considered. This is how it was implemented before.

**Comment by AnnieMungai** [comment]
@hamza-vd @ellykits I would think that the information will still be relevant -- for example we can see the coverage of the facility 3 or more years ago. So when we select a year 3 or more years ago, it means that you see the vaccination coverage for that age of children at that time, not just reports for children at this point in time. It is supposed to be a comparison report. So you can compare year 2017 with 2020 by looking at the reports.

**Comment by AnnieMungai** [comment]
@ellykits I am closing this issue as it already highlighted in issue #127
