### ISSUE TITLE
Post app to Google Playstore

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#117]
Background: ZEIR was rolled out in 2017 in Zambia, and posted on Google play store. However, this application has undergone some improvements in the recent past. The new application needs to be posted on Google play store. 

Required: 1) Post the revamped ZEIR application to Google playstore. 2) Review the requirements for this new application. 
- [x] A short description of the app (up to 80 characters):
As it currently is on the Playstore. 

- [x] Full description of the app (up to 4000 characters)
As it currently is on the Playstore. 
- [x] What's new?
- Updated libraries.
- Booster vaccines added. 
- Out of catchment forms sync. 
- Under 1 and Under 2 fully immunized flags. 
- Other app improvements including Improved UI, 3 z-scores for growth monitoring, record archiving feature. 

- [x] Hi-res app icon (512x512 pixels): 
As it currently is on the Playstore.

- [x] Feature graphic for the apps. More info on the feature graphic here (1024x500 pixels) @HenryRae 
![Feature graphic for the apps](https://user-images.githubusercontent.com/31955469/114375045-f39fe080-9b8c-11eb-9d3a-5c571c2ecd96.png)

- [x] 3 screenshots of the app @HenryRae 
![Screenshot-1b](https://user-images.githubusercontent.com/31955469/114375718-a2442100-9b8d-11eb-915c-2ab86c4c87ed.png)
![Screenshot 6](https://user-images.githubusercontent.com/31955469/113300915-1ae1ec80-9307-11eb-929d-9edcc98737c3.png)
![Screenshot 8](https://user-images.githubusercontent.com/31955469/113300926-1e757380-9307-11eb-8f57-ba4fc7d82635.png)

Similar to [this issue.](https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/32)

**Comment by ellykits** [comment]
@HenryRae kindly provide the required graphics

**Comment by HenryRae** [comment]
done.
cc: @ellykits @AnnieMungai @rowo

**Comment by AnnieMungai** [comment]
Thanks @HenryRae these look good. We shall proceed.

**Comment by HenryRae** [comment]
@AnnieMungai I have replaced the names as requested.
