### ISSUE TITLE
Child's zone area is picking residential areas within the zone on the hierachy

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#121]
- [ ] On the registration form, the child's zone is picking the residential areas in those zones. This should only pick the zones under that facility. For example, for Happy kids, there are 4 zones: Zone1-4. When selecting the child's registration, these are the only zones that should appear as options on the child's registration form. 

![image](https://user-images.githubusercontent.com/58034047/114044726-2184dc80-9890-11eb-89e6-87914d6e1184.png)

**Comment by ellykits** [comment]
Issue is now resolved. See below

![screenshot-2021-04-09_12 45 06 666](https://user-images.githubusercontent.com/26865532/114162178-86dcda00-9931-11eb-999f-f94320a71473.png)
![screenshot-2021-04-09_12 44 53 152](https://user-images.githubusercontent.com/26865532/114162190-89d7ca80-9931-11eb-8296-d9c87cedb324.png)

**Comment by AnnieMungai** [comment]
Looks good!
