### ISSUE TITLE
DailyTallies Enhancements

### ISSUE THREAD

**Issue by hamza-vd** [opensrp/opensrp-client-path-zeir#123]
- [x] Remove daily tallies sync functionality from side menu sync and add a sync button to the HiA2 reports activity app bar for daily tallies sync.
- [x] Add sync start and end toast notification for daily tallies using EventBus.

**Comment by AnnieMungai** [comment]
@hamza-vd just curious, why are we removing the sync from the side menu? I am not sure I fully understand the issue.

**Comment by hamza-vd** [comment]
@AnnieMungai 
We are not removing sync from the side menu, we are just excluding daily tallies functionality from there, rest of the sync functionality will remain the same. We are actually moving daily tallies sync functionality from side menu to inside HiA2 reports by adding a sync button there

**Comment by AnnieMungai** [comment]
@ellykits I was wondering does this improve app functionality at the point of syncing for a 1st user?

**Comment by AnnieMungai** [comment]
V.0.0.10 preview
Looks good.
