### ISSUE TITLE
V 0.0.9 UI QA

### ISSUE THREAD

**Issue by HenryRae** [opensrp/opensrp-client-path-zeir#124]
The new update is missing the active status notification.

Update:
![image](https://user-images.githubusercontent.com/31955469/114367653-50979880-9b85-11eb-93de-2b9ccf60c9b5.png)

Old Screenshot from play store: 
![image](https://user-images.githubusercontent.com/31955469/114367857-89d00880-9b85-11eb-9929-1304f048e0a8.png)

**Comment by AnnieMungai** [comment]
Outdated Issue
