### ISSUE TITLE
ZEIR target not pulling

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#127]
V.0.0.9r2 - preview
The ZEIR target population is showing as 0 children(see screenshot below). This means that the system is not pulling the correct ZEIR target population at all. The ZEIR target population is computed as indicated on [this data dictionary](https://docs.google.com/spreadsheets/d/1_2xuIFr71IgqhWqI8Dwmu2BCR2gfD6LtgC2pJ030nTk/edit#gid=705615058) - row 4. 
![image](https://user-images.githubusercontent.com/58034047/115206390-36b90100-a103-11eb-9695-692481714fb3.png)

**Comment by AnnieMungai** [comment]
@hamza-vd @ellykits [this is](https://github.com/OpenSRP/opensrp-client-path/issues/174) a related issue that was created for the original ZEIR.

**Comment by AnnieMungai** [comment]
**Overview:** The annual ZEIR coverage rate is measured by comparing the number of children vaccinated with a particular vaccine dose and the number in the target population of surviving infants under one year of age (these are the eligible infants) as registered in ZEIR. The result is expressed as a percentage.

- [ ] Tapping the back button in the top left or the back button on the tablet takes the user back to the Coverage Report selection screen.
- [ ]  The Year field at the top is a dropdown, where the user can select which calendar year to view. A year should be added to the drop-down once it starts. 
- [ ] ZEIR Target is the total number of alive children <= 12 months of age [Date_Birth] currently registered in ZEIR for that health facility (this will change over time as health facilities work to register all of the children in their catchment area in the ZEIR app; children will also grow past 1 year of age or move to a different catchment area or can pass away, and would be removed from this count). This is the **denominator for the coverage rate.**

**ZEIR Target 1 (for  <= 12 months of age)** = {All children <= 12 months of age as at January 1st of that year - children <= 12 months of age at January 1st who died - <= 12 months of age at January 1st who moved from catchment area} 

**ZEIR Target 2 (for  <= 24 months of age)** = {All children <= 24 months of age as at January 1st of that year - children <= 24 months of age at January 1st who died - <= 24 months of age at January 1st who moved from catchment area} 
**Note!** The 2nd denominator applies for the MR2 vaccine only!

- [ ] The "Vaccinated" column shows the total number of children in the app (within the allowed age range) who received that particular vaccine dose within the calendar year (see reporting dictionary for the age range). This is the numerator for the coverage rate.
- [ ] The "Coverage" column shows the coverage rate for that particular vaccine dose using the ZEIR target number. This is the number vaccinated divided by the number of children in the ZEIR Target multiplied by 100 and displayed as a percentage (whole number).

**Coverage rate** = {Children vaccinated by a particular vaccine / ZEIR target} * 100

**Note!** For MR2 vaccine - ZEIR target 2 applies while for all other vaccines, ZEIR target 1 applies. 

- [ ] In the Year field, the "(In Progress)" label gets added if the calendar year has not finished yet (not pictured here but pictured in #173). For e.g. 2017 will show "(In Progress)" until January 1, 2018 and so on. When finalized, the coverage numbers can change to blue font (as pictured here).

**Comment by hamza-vd** [comment]
@AnnieMungai 

For **ZEIR Target 1 (for  <= 12 months of age)** let's suppose that a 3 months old child is registered on 30th Jan 2021, having DOB on  30th Oct 2020, who would be 2 months old on 1st Jan 2021. Will that child be eligible for the ZEIR target number for the year 2021?

**Comment by AnnieMungai** [comment]
@hamza-vd yes!! This is because we are not checking when the child was registered rather when the child was born. The ZEIR target in that way is a dynamic target and will change based on dob for children registered in the app.

**Comment by AnnieMungai** [comment]
v.0.0.15r2 - debug
Looks good to me!
