### ISSUE TITLE
Make Residential Area on Registration Form free text. 

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#13]
- [x] Make the residential level on the registration form free text (was previously a location hierarchy). 
- [x] Remove the question on *other* on the registration form.
- Data [dictionary here](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=0) (refer to the Birth Registration sheet - highlighted in purple - rows 24-25).

**Comment by cafootitt** [comment]
@AnnieMungai Looks good, but it would be helpful to say what we're changing it from, since we can't see what the field used to be in the data dictionary.

**Comment by AnnieMungai** [comment]
v0.0.1-r2

Looks great!
