### ISSUE TITLE
Log in + location with production users

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#130]
- [x] User can login but once logged in, the app brings a blank facility name and cant sync anything, and clicking on facility crush the system. e.g the last name below first behaved the same way and we had to delete the app several times and reinstall it until it behaved normally.
- [ ] Users assigned to the wrong facility group; they seem to be assigned to musokotwane and not Katombora (@ellykits can the admin account on Keycloak be able to change the location assignments? 
- User 1: Vlwazo
- User 2: Pnalumango

**Comment by ellykits** [comment]
The remedy would be to clear the data and attempt login - will try to reproduce it. This happen when sync fails immediately after login.

> * User can login but once logged in, the app brings a blank facility name and cant sync anything, and clicking on facility crush the system. e.g the last name below first behaved the same way and we had to delete the app several times and reinstall it until it behaved normally


Team assignment is only available in OpenSRP web. Can you provide their correct locations? It would be great to compile a list of all users experiencing the same; with their correct locations. 
> * Users assigned to the wrong facility group; they seem to be assigned to musokotwane and not Katombora (@ellykits can the admin account on Keycloak be able to change the location assignments?

**Comment by AnnieMungai** [comment]
@ellykits This issue is occuring for a facility - Prisons, user; Mmphiri. 

Try replicate, I have shared with you login details.

**Comment by AnnieMungai** [comment]
V. 2.0.0 -r2
Looks pretty awesome!
