### ISSUE TITLE
Upload Western Province locations and users

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#137]
- [ ] Upload the Western province locations and users on Keycloak - the locations and users can be found on [this](https://docs.google.com/spreadsheets/d/17HYkHhPfBgSYdwLSYv5jutO7rINb5Pek/edit#gid=215877623) and [this](https://drive.google.com/file/d/1U6BFIWVLRrcyPKoRfMPZK5YmulGf3V1c/view?usp=sharing) spreadsheet respectively.

**Comment by tychus6** [comment]
Did a QA on this issue with  random users from every district. All the users were able to login
