### ISSUE TITLE
Review the MVAC code 

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#139]
- [x] Review of the MVAC code to determine the kind of work that is still pending. 
- [x] Confirm the code that is available is workable. 
- [x] Confirm the changes made since the last development. 
- [x] Highlight the LOE required for the code update.

**Comment by ellykits** [comment]
This can be moved to GitHub Discussions @AnnieMungai

**Comment by ellykits** [comment]
I provided feedback for the code review and shared the document.
