### ISSUE TITLE
Ability to edit fields on registration forms and lock editing after 6 weeks

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#14]
Complete fix on the ability to edit and lock specified fields after 6 weeks (on the registration form).

Current status: Once a record is saved, the User has the ability to edit only certain fields while others remain locked. 
Request:  to leave all fields open for editing within the first 6 weeks and later on lock the lockable fields which include: Date of birth, sex, Date first seen, weight, place of birth, HIV exposure status. 
Based on the child registration form on this [data dictionary](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=0). 
Comment: DOB could be a challenge as it will affect the vaccine schedule of the vaccines given. 
Children under 6 months is a common error. Because of the arrangement of the dd/mm/yyyy.
Suggestion: Check the different calendar widgets- drop-down for year, month and date.

Current date picker:
![image](https://user-images.githubusercontent.com/58034047/100626131-78086a00-3336-11eb-8c5b-8e8634a16a60.png)

**Comment by cafootitt** [comment]
@AnnieMungai For tomorrow's call, it would be helpful to provide a list in this issue that shows the current fields in the registration form, and which ones are currently editable vs. not editable, so we can see which fields they want to now make editable. There are probably technical reasons why they are not currently editable, so we'd have to understand what those are.

**Comment by AnnieMungai** [comment]
This is no longer an issue. Editing will not be locked after 6weeks. 
DOB and the gender of the child will not be editable once recorded.
