### ISSUE TITLE
Link ZEIR with DHIS2

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#141]
- [ ] Conduct research on what is required to integrate ZEIR with DHIS2 and document with a scope document- @tychus6 
- [ ] Map the app indicators to the DHIS2 indicators- @AnnieMungai 

QQ: How do you we integrate the indicators from Mvac with those from ZEIR? - point of discussion with @ellykits and @tychus6

**Comment by ellykits** [comment]
This can be moved to GitHub discussions. @AnnieMungai

**Comment by AnnieMungai** [comment]
This was completed.
Required - DHIS2 indicators and names.
