### ISSUE TITLE
Facility users switching between 2 different facilities

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#142]
- [ ] We have an issue with one facility in Southern Province, Linda Clinic in Livingstone district, there are some users that appear to have an issue with the location when logged in, they are switching between the Linda Clinic and Mahatma Ghandi but the children showing on the device belong to Linda clinic. The users can add a child and the Home facility is Linda when registering a child. 
Users highlighted below: 
```
Elina | Miti | elmiti | 
Theresa | Katito | tkatito |
Zacharia | Banda | zbanda | 
```

**Comment by AnnieMungai** [comment]
@ellykits cc @tychus6 I checked out these users and this is what I found:
Zacharia is assigned in both teams. 
Elina - only on Linda clinic (I am not sure how to check whether they are assigned to another team)
Theresa - only on Linda clinic (I am not sure how to check whether they are assigned to another team)

**Comment by ellykits** [comment]
@AnnieMungai Can you comment here the correct locations for the users? I assume the problem was inherited from OpenMRS (some edge case which we did not consider during the migration). I probably think the users were assigned to teams that later got deactivated or something..the import logic was just reading the data as in OpenMRS not doing any processing to determine whether the team is active or not - this is just my theory, I will look more into it.

**Comment by dubdabasoduba** [comment]
@AnnieMungai the only way we can currently show which users is assigned to which team by looking are the team members on the team details sections. 

We can however add the team assignment info on the user details sections. @rowo what do you think about this from a UX point of view.

**Comment by AnnieMungai** [comment]
@ellykits All the users are assigned the Linda clinic. 
As you mentioned this could be an issue with data that is compromised from OpenMRS.

**Comment by AnnieMungai** [comment]
@ellykits aall users at Linda clinic are having log-in issues - if they sync data, the app is crashing.

**Comment by ellykits** [comment]
Let me check the logs in Crashlytics - are they using the latest app?

**Comment by ellykits** [comment]
It appears the crashes reported (between May 31 and Jun 2) are for users using Android version 10.

**Comment by AnnieMungai** [comment]
@ellykits will this solve this issue? https://github.com/opensrp/opensrp-client-native-form/pull/491

**Comment by AnnieMungai** [comment]
v.0.0.13
Will mark this as resolved and observe
