### ISSUE TITLE
Post all URLs on Bitwarden

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#143]
- [ ] Create a ZEIR staging and preview folders on Bitwarden. In each folder, place access details of the following: 
- [ ] OpenSRP
- [ ] OpenSRP Web
- [ ] Keycloak
- [ ] Canopy/superset (once completed)
- [ ] Rapidpro
- [ ] Any other thing that will require access. 
- [ ] Update the production instance with the same details

**Comment by tychus6** [comment]
@AnnieMungai  i have updated the ZEIR folders, kindly review

**Comment by AnnieMungai** [comment]
Thanks! Looks good.
