### ISSUE TITLE
 Include the minimum and maximum level target in the stock module

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#15]
- [ ] Include the minimum and maximum level target in the stock module. 

Current status: Does not include minimum and maximum levels. 
Request:  we visioned this to be projected on the vaccine levels graph under stock planning. A maximum line should project the expected maximum stock levels for the facility and the minimum line should project the expected re-order level for the facility. So if the graph goes beyond the maximum, then they have too much stock and if it goes below the minimum, then they need to reorder. 

Min and max targets assigned based on the catchment area projections. There is a max amount that they can keep in the fridge and min that indicates you need to re-order. The targets can change. Minimum - 0.5 (2 weeks) of stock; Max - 2 months worth of stock. Data is provided from the MOH. 

![image](https://user-images.githubusercontent.com/58034047/100632553-016f6a80-333e-11eb-90e3-02115440e2ca.png)

**Workflow**:
- The HW will receive vaccines based on the number of children with due services. The vaccine stock will update based on the actual vaccinations given. 
- Based on the projections - for active children with due vaccines vs the vaccines utilized- the required number of doses are updated. This updates the vaccine level graph. 
- Based on the target population and the projections for children that will require vaccines, stock required is projected. 
- Minimum targets (minimum recommended vaccine volume to have) will be stock for the next 2 weeks, and maximum targets will be recommended stock for the next 2 months. 
- This is shown on the stock level graph.

**Comment by cafootitt** [comment]
@AnnieMungai Can you try to write up a quick workflow of how this could work? How do they enter the min and max target levels? Are the min and max target levels different for each vaccine type? Can they be edited? Can the vaccine level graph be viewed even if the min and max targets are not entered? 

It would be helpful to include a screenshot of the vaccine level graph on this issue for tomorrow's call (or have it up and ready to show on your emulator).

**Comment by AnnieMungai** [comment]
Zambia has a stock tracking system now. 
Outdated Issue
