### ISSUE TITLE
OpenSRP number/registration form not available with new installs

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#152]
Preview v:0.0.12 
- [x] The registration form is not available for new installs after the first 3 registrations. I synced data but this was still not available. I had to log-out and log in back again. This should not be the case. User should be able to register clients all throughout without the app having any issues or having to log-out and log back in. 
How to replicate the issue:
- Install the application as a new install (for a new user- any user at the Western province Senanga district)
- Register 4 clients and observe. 

![image](https://user-images.githubusercontent.com/58034047/120766919-5c6b5f80-c523-11eb-83df-6278066f3f0a.png)

**Comment by ellykits** [comment]
Unique IDs used to identify clients are synced from the server. I think this was a connection failure/server did not respond timely with the generated ids. I confirmed the IDs are configured correctly.

**Comment by AnnieMungai** [comment]
@ellykits you will need a fresh install of the app on a device. Then register 4-5 children and observe what happens at the 4th child.

**Comment by ellykits** [comment]
I think I have a rough idea why this happened on Preview server. Here is the explanation however I also identified another bug. If you registered 4 children then they are all supposed to be displayed on the main register. I noticed missing mother details for the child whose record is not displayed.

**Comment by ellykits** [comment]
We configure within the app the number of unique ids to sync from the server then we have a task scheduled to periodically to pull more unique ids when the ones synced initially get used up. On preview, the initial batch is 10, then the periodic task is scheduled to run after every 180 mins (3hrs), meaning when all the unique ids are exhausted then they can only be synced after the 3hrs or manually via re-login.

**Comment by AnnieMungai** [comment]
v.0.0.13
Looks good!
