### ISSUE TITLE
Correct aggregation of the HIA2 reports

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#16]
- [ ] Accurate aggregation of the Health Information Aggregate Version 2 (HIA2) reports (Tally sheet/monthly reports)
- Currently this does not populate on most of the tablets. 
- Tally sheets/monthly reports are also off. 
- Numbers on all indicators are inaccurate.

**Comment by cafootitt** [comment]
@AnnieMungai I wouldn't know what or how to start troubleshooting this issue if I were an engineer. It's too vague. There are no steps to replicate, nor any link to the formulas for the HIA2 indicators to verify the current implementation against. Screenshots and specific examples of what you mean by "off" or "does not populate" would also be very helpful. It looks like there are 64 indicators in the HIA2 report, are you saying that all 62 indicators are wrong? How do you know? How did you test this?

**Comment by AnnieMungai** [comment]
@cafootitt after the update of the reporting libraries this issue was resolved. HIA2 reports are loading and computations are correct.
