### ISSUE TITLE
App stopped responding when recording growth data or trying to edit the data

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#160]
v.0.0.13- preview
Android 10 results

- [ ] When recording growth data for a child, at about 3rd or 4th recording, the app stops responding and crashes when you try to save the data or add the date. The weight and height are however recorded upon login.
- [ ] Same thing happens when you try to edit recorded growth data. 
![image](https://user-images.githubusercontent.com/58034047/122010522-dde4ac80-cdc3-11eb-9192-90d30bd54210.png)

Note! No issues were observed with Android 7.

**Comment by paulinembabu** [comment]
@AnnieMungai I am not able to Reproduce this. The issue might have been fixed when the Native forms issue was Resolved. We can test this out in the Next Release

**Comment by AnnieMungai** [comment]
v.0.0.14- debug

Looks good to me!
