### ISSUE TITLE
[MVACC] Update the client mobile app to show the system of registration

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-path-zeir#168]
**Context**
- We are registering clients into the ZEIR server from 2 different platforms. This is ZEIR mobile app and the mVacc system. 
- We need a way to tell the users that the patients were registered from either platform. 

**Technical Implementation**
- [ ] Add an attribute called `system_of_registration` to the ZEIR client object details attribute -- Server Work
- [ ] Update the mVacc registration piece to populate this `system_of_registration` attribute with the value `mvacc` during each registration. --- Server Work
- [ ] Display this attribute on the patient profile on the ZEIR mobile app.  The display should be worded as follows `System of Registration: mVacc`. 
- [ ] This display on the profile should only happen under the following circumstances. 
    - [ ] The `system_of_registration` attribute is available in the client object.
    - [ ] The `system_of_registration` attribute has the value `mvacc`

**Other Nice to have pieces**
- [ ] If a client object has the `system_of_registration` attribute, add a step that will also redirect the user to the registration page to complete the child registration. This should be governed by the following flow. 
    - [ ] Add another attribute to the client object, this attribute should be named `is_registration_complete`. The value should be `true` or `false`
    - [ ] The mVacc registration piece should set the `is_registration_complete` to `false`
    - [ ] For the ZEIR mobile app to redirect the user to the registration form the following should be the case.  The `is_registration_complete` should be `false` and the `system_of_registration` should be `mvacc`. Otherwise, the app should proceed with its normal behaviour. 
    - [ ] Once the user updates the registration the `is_registration_complete` should be marked as `true`

**Acceptances criteria**
- The user should be able to see the system of registration on the child's profile page
- The app should be able to redirect the user to the registration page if the registration details have not been completely filled in and the patient was registered from mVacc
- The app should not redirect the user to the registration field once all the registration details have been completely filled in.

**Comment by dubdabasoduba** [comment]
@AnnieMungai I am not sure where in the profile we need to see the `system_of_registration` flag. We might need @rowo input if we can't figure it out. 
Also, check on the `Nice to have pieces` to see if they are good for making sure that the registrations details are always updated.

**Comment by ellykits** [comment]
@AnnieMungai Kindly update this issue with the RapidPro consent flow that needs to done on the form. Also remember to update the data dictionary.

**Comment by ellykits** [comment]
@dubdabasoduba I have gone through the **Nice to Have** section and had the following question, what will be the metric to use for determining that the registration is complete? as most of the fields in ZEIR are non-required.

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba I have gone through the **Nice to Have** section and had the following question, what will be the metric to use for determining that the registration is complete? as most of the fields in ZEIR are non-required.

Do we have any required questions we need to fill? If so we can check if those are filled then assume the registration is complete. 

@AnnieMungai or @tychus6 do you have an idea of any fields required on ZEIR but aren't collected on mVacc

**Comment by AnnieMungai** [comment]
@dubdabasoduba this was updated on the [scope document](https://docs.google.com/document/d/1FI_J41fev9-8xDrOhLTH2-0bI80SGMuQlflkIv1rOzU/edit#).

**Comment by AnnieMungai** [comment]
Flags to use for this:
On the main register
![image](https://user-images.githubusercontent.com/58034047/127470347-4dc5a337-416b-4313-84be-568a9cff7605.png)

On the child profile
![image](https://user-images.githubusercontent.com/58034047/127470985-d2bcc4e7-0d91-4278-8ac7-c4a833bce7be.png)

**Comment by AnnieMungai** [comment]
@junaidwarsivd as discussed during the stand-up, here are some enhancements for this implementation:
- [ ] Change the colour of the MVACC label to green and bold it to make it more visible. 
- [ ] Add space between the C/giver name and MVACC label on the main register to separate the 2 and make it clear they are different items. 
- [ ] Add space between child age and MVACC label on the child profile to make it clear these are distinct and separate items.

**Comment by junaidwarsivd** [comment]
@AnnieMungai  @tychus6  i have updated the apk with the enhancements added above you can install the update from this link 
https://github.com/opensrp/opensrp-client-path-zeir/releases/tag/v0.0.19

**Comment by AnnieMungai** [comment]
Looks great! The green really pops.
