### ISSUE TITLE
ZEIR dashboard enhancements

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#171]
- [ ] Add the ZEIR logo on the dashboard. 
![image](https://user-images.githubusercontent.com/58034047/125749625-34e18d34-e30e-4c30-989f-484e252930c1.png)
- [ ] Filter controls to be at the top of the page. 
![image](https://user-images.githubusercontent.com/58034047/125765995-98aea75a-75de-4d26-9a94-7cf0f99d6468.png)

**Comment by muneneg** [comment]
@AnnieMungai I have added the logo and arranged the filters as requested. Please review.

![image](https://user-images.githubusercontent.com/41571129/131318407-3ef96816-aee6-46d4-8621-22cf4f65fea5.png)

**Comment by AnnieMungai** [comment]
Looking good!
