### ISSUE TITLE
Testing the flows on Rapidpro + OpenSRP

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#174]
Test Vaccination + growth monitoring flows 
- [ ] Syncing the from Rapidpro to OpenSRP
- [ ] Syncing from OpenSRP to Rapidpro
- [ ] Single vaccine administration

**Comment by tychus6** [comment]
@ellykits  I  found the following issues while testing ZEIR-MVACC integration:
1. When you add a child on ZEIR App, the child doesn't appear on Rapid pro after syncing. Sample children are Allan and Stacy.
2. When you add a child on MVACC, the child doesn't appear on ZEIR after syncing . Sample children are Fatuma and Kadima.
3. After a child has been registered on MVACC, the OpenSRP ID(ZEIR ID) and facility_location_id are not updated on  Rapid pro contacts. Sample children are Fatuma and Kadima.

**Comment by dubdabasoduba** [comment]
> @ellykits I found the following issues while testing ZEIR-MVACC integration:
> 
> 1. When you add a child on ZEIR App, the child doesn't appear on Rapid pro after syncing. Sample children are Allan and Stacy.
> 2. When you add a child on MVACC, the child doesn't appear on ZEIR after syncing . Sample children are Fatuma and Kadima.
> 3. After a child has been registered on MVACC, the OpenSRP ID(ZEIR ID) and facility_location_id are not updated on  Rapid pro contacts. Sample children are Fatuma and Kadima.

@tychus6 Did this happen even after giving it sometime to sync?

**Comment by tychus6** [comment]
@dubdabasoduba  Yes
