### ISSUE TITLE
Flag for children registered on MVACC on ZEIR app

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#177]
Background: ZEIR-MVACC integration requires registration of children on ZEIR and MVACC. Children registered in either system can receive services from CBVs (on MVACC) or Health providers (at the facility). CBVs use MVACV while health providers use the ZEIR application. For this phase of work between ZEIR and MVACC, one of the requirements is to have a flag that differentiates the children that are shown on the ZEIR application but were registered in MVACC. 

**Required**: A flag that shows all children that are registered on MVACC. 
**Nice to have**: A way to also show children registered on ZEIR. 
**Suggestion**: Have a flag that identifies clients that have been registered via mVACC and no flag for children registered via ZEIR. 
Related to issue #168. 
We could use flags that are used on ANC or those that are used on Malawi child module and indicate _mVACC_ However, we still need a UI for flags on the child profile or we could totally design new flags for this. 
@rowo what are your thoughts on this? 
![image](https://user-images.githubusercontent.com/58034047/127018811-19ad524d-f1cc-4737-92f4-21e3c6ec88d6.png)

**Comment by rowo** [comment]
@AnnieMungai 
- What's the value/need to show which app they were registered in at the list level?
- How many of the children would be registered via MVACC vs not?
- Flags in existing use cases are more as an indicator of risk/priority. Is this that important? 
- If a user saw this visual indicator (whether flag or label or something else), would a user know what it means and how it impacts things?

**Comment by AnnieMungai** [comment]
@rowo 
1. For the children that are registered on MVACC, not all details are captured on ZEIR and captured during registration on MVACC. The flag is therefore an identifier kind of thing for the health worker at the facility to fill in all the missing details on the registration form. 
2. At the moment it is likely that most children will be registered on ZEIR vs on MVACC as ZEIR is a system that has been fully in use since 2018. 
3/4/5. This is not a priority indicator. It is more like identifying info.

**Comment by rowo** [comment]
Conclusion
- De-scoped to not be a task i.e. "registration incomplete" status and instead just MVACC-registered. OpenSRP user will just check registration info form for completeness every time they encounter an MVACC patient.
- If using label, then "MVACC" is sufficient to communicate this status.
- Need to appear on profile and list
- This is for facility so it's not like MVACC-registered clients are targeted

**Comment by rowo** [comment]
@AnnieMungai If you have quick access to these items, can you share:
1. screenshot of the current register list view 
2. screenshot of the current child profile view
3. data dictionary for MVACC registered clients

**Comment by AnnieMungai** [comment]
@rowo 
1. Current register view
![image](https://user-images.githubusercontent.com/58034047/127352753-4e1ffc58-acc8-4f47-960c-413d1fdfbe82.png)
2. Current child profile view
![image](https://user-images.githubusercontent.com/58034047/127352837-cd7e24fe-c45a-433a-86f4-180c7fe86958.png)
3. For the data dictionary: pages 5-7 of [this document](https://docs.google.com/document/d/1FI_J41fev9-8xDrOhLTH2-0bI80SGMuQlflkIv1rOzU/edit#) displays fields captured on MVACC.

**Comment by AnnieMungai** [comment]
Updated: 
![image](https://user-images.githubusercontent.com/58034047/127469897-292ba0a5-e9ea-47e6-a737-e844d41e7ac4.png)
![image](https://user-images.githubusercontent.com/58034047/127469914-a856a51d-35d7-489e-a8a4-d7bd4775381c.png)

**Comment by rowo** [comment]
Okay I updated https://github.com/opensrp/opensrp-client-path-zeir/issues/168#issuecomment-888974345 with a few more details.
