### ISSUE TITLE
Dashboard sections additions and amendments

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#189]
- [ ] Amend the dashboard sections to read as follows:
1. Summary
2. Immunization
3. Coverage and drop-out reports
4. Growth monitoring and nutrition
- [ ] Move the dropout reports and coverage reports from the immunization section to the coverage and drop-out reports
![image](https://user-images.githubusercontent.com/58034047/130229413-c16e3c89-7781-452b-b715-75577b21c7be.png)
- [ ] Remove the time column on the Immunizations by facility per antigen in a given period table. 
![image](https://user-images.githubusercontent.com/58034047/130229607-910beb37-1b87-4f6b-8a13-760880248950.png)

**Comment by muneneg** [comment]
@AnnieMungai I have made these changes, please review.

![image](https://user-images.githubusercontent.com/41571129/131318860-dc7a363c-38e0-4448-bb07-925add29e09a.png)

**Comment by AnnieMungai** [comment]
Looks good!
