### ISSUE TITLE
Automatically archive child records when they get to 5years 

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#19]
- [ ]  System to automatically archive child records when the child reaches the age of 5years.
- [ ] This is not currently happening and the children over 5yrs can still be seen in the child register. Ideally, the system should archive records when a child gets to the age of 5years. Once a record is archived, it should no longer be visible on the child register. 

![image](https://user-images.githubusercontent.com/58034047/101342163-3b3af680-3893-11eb-9313-847053e6f285.png)

**Comment by cafootitt** [comment]
@AnnieMungai What are the steps to replicate the dashboard issue? How do you know the over 5 children are being included in the dashboard? Do you mean the in-app reports or the Canopy dashboard?

**Comment by AnnieMungai** [comment]
v0.0.1-rc4

Looks good!
