### ISSUE TITLE
Add an year and month filter button

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#190]
- [ ] Add a year and filter button on the ZEIR dashboard to allow users to select specific months and years filters. See the example below:
![image](https://user-images.githubusercontent.com/58034047/130231201-e7df0ed1-cea5-44d1-bd6d-e4d737043e4e.png)

Example: [Tunisia dashboard](https://superset.unicef-tunisia-stage.labs.smartregister.org/superset/dashboard/7/)

**Comment by muneneg** [comment]
@AnnieMungai I have added these filters, please review.

![image](https://user-images.githubusercontent.com/41571129/131318308-a176ab50-3a12-4ed3-8567-91c1633c5780.png)

**Comment by AnnieMungai** [comment]
Looks good!
