### ISSUE TITLE
Standardise Read ME doc

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#2]
OpenSRP projects Read Me are required to follow this template.
https://github.com/onaio/opensrp-tasks/blob/master/README.md.template

**NB:** The sections required for update are those with angle brackets on the template

**Comment by AnnieMungai** [comment]
@ellykits please add link to this.

**Comment by ellykits** [comment]
Closing. Already added to new ZEIR app.
