### ISSUE TITLE
ZEIR-MVACC Integration: QA feedback (ZEIR)

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#203]
- [ ] When you give the OPV vaccine on MVACC for a child who did not receive OPV0 (it is a vaccine that can be skipped to activate OPV4), instead of the OPV4 updating, OPV0 updates, even when the child has already received OPV 1-3. 
- [ ] Expired vaccines not updating on ZEIR even if the child receives them on mVACC --- I may need to understand what the logic for expired vaccines is on MVACC.
- [ ] When more than one batch of vaccine is recorded for a child. Example 4 weeks and 6 weeks --- the 4 weeks vaccine update but not the 6 weeks. ---may need to change or understand the vaccination flow.  
- [ ] It is taking a while to update vaccines given on mvacc on ZEIR. Ideally how long should this take if the ZEIR user triggers a manual sync?

cc @tychus6 @ellykits

**Comment by ellykits** [comment]
@AnnieMungai To answer the first question:


> * When you give the OPV vaccine on MVACC for a child who did not receive OPV0 (it is a vaccine that can be skipped to activate OPV4), instead of the OPV4 updating, OPV0 updates, even when the child has already received OPV 1-3.

RapidPro flows do not apply any logic for the vaccine entries. We do not have any vaccine schedule implementation on the server side, we just receive and store the vaccination event event as is. When a vaccination field is updated in RapidPro contact  we process it into a new event the first time and ignore any future update for that vaccine record. Assumption is vaccination can only be administered once.

The remaining items are related. An exception was caught preventing processing of new contacts.
