### ISSUE TITLE
ZEIR-MVACC Integration: QA feedback (MVACC - User testing) 

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#204]
- [x] Was allowed to register a child  (Ndegwa) even without adding the name of the caretaker or the village. System confirmed registration but this child did not appear on ZEIR. Question: Should a child registration be complete without all the child details? Should the user be told to add the correct details to complete the registration? 
- [ ] When recording Penta vaccines, there are discrepancies in what the user enters and what the system brings back for confirmation. Use asked to enter Penta vaccine but return message says DTP vaccine. Make these read the same for both messages. 
- [x] When using MVACC ID -- system only picks the last 3 numbers on the ID. Need to be very specific on how the MVACC ID should look like during registration. Q. What happens if someone inputs an MVACC ID that is more than 3 numbers?  For example- system allows user to register a child with MVACC ID 4012/2020  but then the system is only able to read 012/2020
- [x] ZEIR ID - not clear the format this should be entered in the system. Is it only 6 numbers or is it 6 numbers + Year? Clarify this format in all the places that users can use the ZEIR ID. 
- [x] Can record more than 1 batch of vaccines on MVACC example 4 weeks and 10 weeks vaccines. ZEIR will only update the 4 weeks vaccines because according to vaccine logic, if 4 weeks vaccines are given today, then the 10 weeks vaccines become active/available in 4 week's time. . Q. Are users allowed to record more than 1 batch of vaccines? 
- [x] Yes, No confirmation message--- asking the user to input Y/N (this is an inconsistency that should be cleared to have uniform responses).
- [ ] The NAME workflow - this updates child's details on MVACC - was this flow factored in ZEIR integration? @tychus6 
- [x] When recording the Measles vaccine (MR1) and OPV - trying to record this in the order of MVACC ID+OPV+MR does not work. The system only allows MVACC ID+MR+OPV ---should this order even matter?Users should be able to record whichever vaccine first. 
- [x] Weight and Height - not clear whether it is in cms or meters and grams of kgs --- need to update the growth monitoring flow to read cms and kgs for height and weight respectively. 
- [x] Could not record growth on MVACC - it does not reflect on ZEIR.

**Comment by tychus6** [comment]
@AnnieMungai  some issues have been resolved as indicated, others are currently been worked on. The NAME flow was not factored in the integration piece. There are other issues that I need further clarification, hopefully, we can go through them in our standup.
