### ISSUE TITLE
Additional issues on ZEIR-MVACC integration

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-path-zeir#206]
- [x] When you record height/weight on mvacc,  it's not reflected on  ZEIR after sync.
- [x] When  you register a child in mvacc  and record vaccines administered on ZEIR, the vaccine information is not synced back to mvacc
- [x] After registering a child on ZEIR,  the child's details appear on mvacc and not the mother's details also the vaccination details dont appear on mvaccc . sample child Faith Aloo 

Additional Items - 30th Sept
- [x] Children registered on MVACC not visible on ZEIR.

4th Oct
- [x] Events generated from MVACC showing a null date on ZEIR. (Current workaround on client end will ensure no force close on app). Some server-side work needs to be done to ensure the events processed are shown correctly - could be a sync issue. 
@dubdabasoduba you can add the technicalities. 
- [x] Children and caregivers recorded on ZEIR not being picked up on MVACC even when a phone number is provided.

**Comment by AnnieMungai** [comment]
Additional issues
- [ ] Events generated from MVACC showing a null date on ZEIR. (Current workaround on client end will ensure no force close on app). Some server-side work needs to be done to ensure the events processed are shown correctly - could be a sync issue. 
-
