### ISSUE TITLE
Remove the Measles Vaccine in the Schedule

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#21]
Context: Initially, the Measles vaccine in Zambia was given either as an MR dose or a Measles dose. This however changed and the country now gives the vaccine as MR (see the [immunization schedule](https://docs.google.com/spreadsheets/d/1XjdrzwvJ4lm03mp59uyLYAvI-m2RxE0HFNjlDuq9e0w/edit#gid=0) - highlighted in pink)
- [x] Remove Measles 1 and Measles 2 from the vaccine schedule. The child will now receive MR1 (at 9 months) and MR2 (at 18months). 
- [x] Measles 1 and 2 should not appear on the child profile. 
- [x] Measles 1 and 2 should not appear on the child history page.
- [x] Measles 1 and 2 should not be available for editing. 
- [x] Remove Measles 1 and 2 on the out of catchment form.

**Comment by cafootitt** [comment]
@AnnieMungai Let's check with @ellykits, but I think this is just updating the labels in the app, because it was a single vaccine that was labeled "Measles / MR 1", so we don't need to "remove" a vaccine, per se.

**Comment by AnnieMungai** [comment]
V. 0.0.1-rc3

Looks good!
