### ISSUE TITLE
App Freezing in several occasions - Production

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#211]
V.2.0.3r2 (Prod)
Tested on Android 5 and 9 (issues reporting for all android versions)
- [ ] When a user is trying to search for a client at the search bar - the app is freezing and throws the message 'ZEIR not responding. The system freezes when typing the ZEIR ID or Child's name, for about 30 seconds for what you type to appear in the search bar.
Note! The app shows this error message after the initial sync too and several when conducting different tasks on the app. 
![image](https://user-images.githubusercontent.com/58034047/134136266-58678aff-a25d-4014-a90c-47bf8afe260f.png)
- [ ] When the user navigates back to the main register (canceling search or tapping back from a child profile) - it shows a white screen without loading clients for some time.
![image](https://user-images.githubusercontent.com/58034047/134136051-7f780c90-e648-43c2-a413-3cb6ec3601ed.png)
- [ ] When trying to re-login back to the app once it crashes- it shows a black screen before loading the clients. You need to give the device some time to load clients even though the initial sync had been completed. 
- [ ] The filter button on the app is super slow and takes awhile to respond.
Note! There seems to be a slowness to the app when loading clients. 
- [ ] When the user tried to register a child on an Android 5 device, app throws a fatal error and stops responding. 
![image](https://user-images.githubusercontent.com/58034047/134137358-9a593b4e-1a3d-4708-83f5-78385672a475.png)

**Comment by dubdabasoduba** [comment]
@AnnieMungai Do you have an idea of what device specs this app is running on?

**Comment by AnnieMungai** [comment]
@dubdabasoduba any device we test this out with is showing the same issues.

**Comment by AnnieMungai** [comment]
v.0.0.25
Looks good!
