### ISSUE TITLE
Sync of Mother Details from MVacc Failing

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-path-zeir#234]
When a child is registered on MVacc and synced to the OpenSRP APK (ZEIR) the mother name is returning as `Mama Majina` as opposed to the name provided when the child was registered on MVacc. An example is the child `Melvis Kim` with ID  `444/2020`. The mother name provided on MVacc is `Janet Jeffer` as per the screenshot below but appears as `Mama Majina` on the ZEIR App.

![image](https://user-images.githubusercontent.com/5908630/141443011-087f1bf6-9105-421c-8708-85f50fff4e8e.png)

**Comment by dubdabasoduba** [comment]
@samkanga What phone number have you used for the mother. Right now the mother phone number is used to identify mothers while trying to register them. If they have the same phone number then we don't create a new mother we use and exisiting one.

**Comment by samkanga** [comment]
@dubdabasoduba thank you for the insight. Let me retest with that in mind.

**Comment by samkanga** [comment]
@dubdabasoduba I confirm this is now working. I will go ahead and close the ticket.
