### ISSUE TITLE
Code Refactor to new code base

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#3]
Refactor ZEIR old code to a new code base. 
- [x] Immunization schedule
- [x] Child profile and registration
- [x] Edit menu
- [x] In-app registers

**Comment by ellykits** [comment]
Closing this as we have all the work from the old zeir app in the new code base. The only work that is missing is syncing HIA2 reports to DHIS which we will work on separately.
