### ISSUE TITLE
Replace Card ID with ZEIR ID on the Advanced Search Page

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#30]
Background: Currently on the advanced search page, the user is able to search for a child using the Card ID. 

- [x] Change the label from `Card ID` to `ZEIR ID` on the advanced search page
- [x] The `ZEIR ID` search parameter should search for the child's record using the ZEIR ID assigned to the child during registration.
- [x] The ZEIR ID should be automatically populated when a user taps on the **_Scan QR code_** button and scans the QR code on the child's vaccine card 
- [x] The user should also be able to manually type in a ZEIR ID. Previously, the user was not able to manually input the ZEIR ID. 
Issue related to this [one](https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/77).

**Comment by AnnieMungai** [comment]
@cafootitt I am not sure how the Card ID worked. So I highlighted how the ZEIR ID should work. 
On the question whether some things broke, when the code was ported over, some functionality was lost. The issue highlights how Advanced search should work. just to make things super clear.

**Comment by cafootitt** [comment]
@AnnieMungai Ok, I updated the issue a bit, can you take a look? Hopefully that makes it a little clearer what changes to make. Can you also separate the bottom two points into a new issue? They seem unrelated and the issue title doesn't reflect that work either.

**Comment by AnnieMungai** [comment]
V. 0.0.1R6
Looks good.
