### ISSUE TITLE
Implement booster vaccine recording on the child profile

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#35]
Implement the booster vaccines page- see this [[scope document](https://docs.google.com/document/d/1NnU_hOwhoyBiedFkxa7ravZHd8xs8krrloZ7tQsJG0I/edit)] - Issue closely related to [this one](https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/35). 
- [x] The page is accessible from the child's profile top right-hand menu. On the menu, add **Record Booster Immunizations**
- [x] Tapping on this will open the **Booster Immnuzations** form.
![image](https://user-images.githubusercontent.com/58034047/105853846-31ae4f00-5ff7-11eb-90e6-1280f69e74d1.png)
- [x] The form will have the option to add a vaccine dynamically- have a +sign that the user can tap, this will display a list of all vaccines available for selection (see [data dictionary here](https://docs.google.com/spreadsheets/d/1dNl_WGxa0WXfx7IHfcu5Bn3WsoTkcKHEfTgo7gCPONY/edit#gid=0))
- [x] A user can add 1 vaccine of each type once only. For example:  a user can only add MR vaccine once. If a child is given OPV dose and MR then user should be able to record OPV and MR dose (only 1 dose of each). 
- [x] The user should be required to add the date the vaccines selected were added. 
- [x] Tapping on the SAVE button will save the record and navigate the user back to the child's profile.
- [x] Once a vaccine has been added, it will appear on the child's vaccine history page at the bottom after the scheduled vaccines. The sub-header will read **Booster Immunizations**.  It will show the dates that the booster immunization was given and show a blue mark against it to show that the vaccine was given to the child. 
![image](https://user-images.githubusercontent.com/58034047/105855436-20fed880-5ff9-11eb-85bf-6dadf593ae64.png)

- [x] If a child has received any booster vaccine, this will also appear on the child's vaccine card as a vaccine that has already been given. The vaccines will be listed under a subheader **Booster Immunizations**.  NB! This header and booster immunizations given only appear when a booster immunization has been given to the child. If a child has not received a booster vaccine, this header will not appear on the child immunizations page. 
![image](https://user-images.githubusercontent.com/58034047/106084607-b3a19380-612f-11eb-9ca1-d777b24b6ea2.png)

**Comment by cafootitt** [comment]
@AnnieMungai If we're modeling this off of the Tunisia private sector vaccine form, then can you please include a screenshot of that here? In the Tunisia form, is the vaccine selection a repeating group? Right now, in your data dictionary for this issue, you have the data type is a select one, which means they can only select one vaccine per form submission, so I think you want this to be a repeating group or a select multiple.

**Comment by AnnieMungai** [comment]
@cafootitt currently there is a bug on Tunisia that is not allowing me to open this page, I will add the screenshots once that is fixed.

**Comment by AnnieMungai** [comment]
@cafootitt currently there is a bug on Tunisia that is not allowing me to open this page, I will add the screenshots once that is fixed.

**Comment by cafootitt** [comment]
@AnnieMungai Thanks for updating the issue. I imagine design-wise, this will just be modeled off of the Tunisia private sector form that we worked on with @rowo. I would just double-check with him and share this issue to make sure he doesn't have any concerns with this approach.

**Comment by rowo** [comment]
@AnnieMungai Modeling this off of the similar private sector vaccines makes sense to me. However, this approach isn't very scalable since it adds new sections for every service variation, so I'm not sure if this is a pattern will carry through from a product perspective. 

Sort of related question though — will the health worker really be clear on where to record information? Essentially now they are looking at 4 spots = schedule vaccines, recurring services, dynamic private vaccines, and booster vaccines — which is a bit to keep track of. And will booster vs. dynamic vaccine vs. scheduled vaccine always be very clear to a health worker while with a particular patient i.e. the service category will never be ambiguous?

**Comment by AnnieMungai** [comment]
v.0.0.4
- [ ] Vaccines are seen on the child history page but are missing on the actual vaccine card page. @ellykits 
Everything else looks good.

**Comment by AnnieMungai** [comment]
Will create an issue to add the vaccines on the child's immunization page.
