### ISSUE TITLE
Sync issue with out of catchment records

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#4]
**Context:** When a child visits a facility that they do not normally visit, they will not be on that facility's register. These children are referred as children out of catchment area. Any services received by these children will be recorded on the out of catchment area form. This form is accessible to the user while they are both offline and online. Once data is synced, the services recorded on the out of catchment area form for the child will be synced with their record at home facility. This will thus update their record with the services given. For example; if the child received OPV 1 that was recorded in the out of catchment form, their record will update with the OPV 1. 
- [ ] Recording vaccines using the offline **out of catchment form** should update the child vaccine card after synchronization for a child out of catchment. The vaccine given should reflect on the main child's record. This synchronization is not currently happening.

**Comment by cafootitt** [comment]
@AnnieMungai What would be helpful here is a list of steps to replicate current vs. expected behavior (including usernames of different dummy users one can use to test this). We have new engineers working on this project, so it would be helpful to define what everything is and where everything is, since they may not know what you're referring to when you say "offline form" or "out of catchment".

**Comment by AnnieMungai** [comment]
@cafootitt this issue is affecting all the EIRs. The engineers on the projects will convene in January to investigate what the problem is.

**Comment by AnnieMungai** [comment]
This requires an additional user for testing.

**Comment by AnnieMungai** [comment]
v.0.0.4
Not working.
@ellykits does the format of the ZEIR ID matter? I have tried all combinations (without a dash, with a dash for a number).

**Comment by ellykits** [comment]
Issue resolved. ZIER ID should not have dashes. The dashes are just added for UI presentation.

**Comment by AnnieMungai** [comment]
v.0.0.8-preview
Looks awesome!
