### ISSUE TITLE
Incorrect figures being pulled on the HIA2 reports

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#64]
1. HIA 2 daily tallies: However, the following are the anomalies: 
- [x] Under 5 Clinic Attendance reports – Numbers being pulled but not accurate,
- [x] Growth Monitoring – Numbers being pulled but not accurate
- [x] Vitamin A, deworming and ITN’S - Numbers being pulled but not accurate 
- [x] Immunization – No figures are being pulled

2.  Draft reports: the following anomalies have been noted:
- [x] Under 5 Clinic Attendance reports – Numbers being pulled but not accurate,
- [x] Growth Monitoring – Numbers being pulled but not accurate
- [x] Vitamin A, deworming and ITN’S - Numbers being pulled but not accurate 
- [x] Immunization – Incorrect figures being pulled - most indicators are not reflecting the correct numbers.

**Comment by hamza-vd** [comment]
@AnnieMungai 

Can you please explain or give some details about why this issue is failing QA? Which scenarios are failing and the user used for testing?

**Comment by AnnieMungai** [comment]
Some o the issues noted for the reports:
1) The outreach numbers are not reflecting on the reports- when a user changes a location to a zone, any services rendered should be recorded as an outreach service.

**Comment by AnnieMungai** [comment]
V. 0.0.10 preview
Looks good.
My only concern is- how long does someone have to wait for all services rendered to show? @ellykits
