### ISSUE TITLE
App giving complete syc notification severally while sync is ongoing

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#68]
- [ ] App constantly saying sync complete during sync - even if sync is not complete. User cannot know when the sync is truly complete. (Seems for every record completed, it is notifying user hence the constant sync completes). 

@ellykits @hamza-vd we can discuss this issue if it is not clear when you pick it up.

**Comment by ellykits** [comment]
I was able to reproduce and fix this bug.

**Comment by AnnieMungai** [comment]
v.0.0.8preview
Looks good.

Noted another sync issue-highlighted on this issue.
