### ISSUE TITLE
Add IPV in the immunization schedule

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#7]
- [x] Include IPV (Inactivated polio vaccine) in the child immunization schedule.
- [x] The vaccine is to be given at 14weeks as per immunization schedule [here](https://docs.google.com/spreadsheets/d/1XjdrzwvJ4lm03mp59uyLYAvI-m2RxE0HFNjlDuq9e0w/edit#gid=0). All other vaccine rules remain as indicated on the schedule. 
- [x] Once added to the schedule, the IPV dose should be visible on child's immunization card under the 14weeks vaccines. 

- [x] Add IPV in the out of catchment form as per the data dictionary [here](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=1173845481) (row 26, highlighted in green). 

- [x] IPV will appear on the child profile on the vaccination card on the 14 weeks vaccines set - as shown in the figure below:
![image](https://user-images.githubusercontent.com/58034047/101789047-dccf7b80-3b11-11eb-8400-3832e3a2a4a7.png)
- [x] IPV vaccine will be shown on the **under 5 history** page. 
![image](https://user-images.githubusercontent.com/58034047/101790028-0937c780-3b13-11eb-82a6-ccfa5fa8ef16.png).
- [x] If IPV has been given to a child, it should be available for editing on the edit menu.

**Comment by cafootitt** [comment]
@AnnieMungai The second point requires discussion/clarification on what the client is asking for here. This could mean a number of different things. Do they mean that they (the client) would like to be able to update the immunization schedule themselves? Right now, this has to be done on the engineering side.

**Comment by AnnieMungai** [comment]
@cafootitt from what I understood, they want to be able to add a vaccine themselves if it changes. If for example an IPV vaccine in added to the schedule, they want to be able to add it themselves. I am not sure whether this is technically viable at the moment though.

**Comment by cafootitt** [comment]
This is more of a technical discussion on feasibility and LOE. My sense is this isn't something we can do under the current scope of work, but let's discuss with Elly/Martin to see what's involved in adjusting the immunization schedule. A good first step could be to check in on the other immunization projects and see if they've fielded a similar request before.

**Comment by AnnieMungai** [comment]
@cafootitt I ahve seprated this issue with the one for adding vaccines when they become available as they seem to be independent issues. We will discuss this further to see how viable it is. #18

**Comment by cafootitt** [comment]
@AnnieMungai I would walk Hamza through the service schedule spreadsheet, so he understands what each of the columns means. The service schedule spreadsheet looks good.

Also, if we're adding a new vaccine, what else is impacted in the app? I think this issue needs to include screenshots and instructions for how the IPV vaccine will be added on the vaccine card page, history page, etc. Listing out all the places where IPV needs to be "added" will be helpful. What about reports? What about out of area catchment form? What about stock module?

**Comment by AnnieMungai** [comment]
@cafootitt I had separated the IPV in reports as a separate issue #17. I am slowly scoping out all the reports that require adjustment to include IPV. I have amended the issue to include all other areas this will change.

**Comment by AnnieMungai** [comment]
V. 0.0.1-rc3

Looks great!
