### ISSUE TITLE
ZEIR: Deploy OpenSRP Web staging server

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#76]
- [ ] Deploy OpenSRP Web for ZEIR staging. 

Expected delivery date: 20th April 2021.

**Comment by dubdabasoduba** [comment]
@AnnieMungai We will require the following items. 

- [ ] When is the deadline for this deployment. 
- [ ] What URL are we deploying to? 

We will only be enabling the following modules for this deployment
- User management includes user creation, user groups assignments & creation & roles viewing
- Location management. 
- Team management includes adding practitioners to teams, assigning teams to locations

**Comment by AnnieMungai** [comment]
@dubdabasoduba I have edited issue and added timelines. @tychus6 are you able to provide the rest of the items?

**Comment by ellykits** [comment]
> What URL are we deploying to? 

URL: **web.path-zeir-stage.smartregister.org**

> Keycloak realm to be used

Ream: **path-zeir-stage**

> OpenSRP server to be used

Server: **latest**

> Credentials to login to the realm and to OpenSRP

Credentials: **Available on BitWarden**

**Comment by AnnieMungai** [comment]
@dubdabasoduba @KipSigei
