### ISSUE TITLE
Users not able to log into the app while not connected to the internet

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#79]
- [ ] Users are not able to log into the app if not connected to the internet. The users are connected to the internet the very first time they log into the app but when they turn off the internet and try logging in, they are asked to connect to the internet. The user should be able to log into the app while offline after the initial log-in. 
![image](https://user-images.githubusercontent.com/58034047/110341777-c5822a80-803b-11eb-9625-34f594b4f628.png)

- [ ] App also keeps login out users  - even if the app is still active and in use.

**Comment by hamza-vd** [comment]
@AnnieMungai 
Can you please attach a screenshot with the error message?

**Comment by AnnieMungai** [comment]
v.0.0.6debug
Looks great!
