### ISSUE TITLE
App logging out users in the first 30 secs after logging

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#80]
- [ ] Users reported to be logged out after 30sseconds after initial login. After a few trials the users were able to log into the app and conduct sync. 
Note! I was not able to replicate this. Could be an internet issue?

**Comment by hamza-vd** [comment]
@AnnieMungai 

We fixed an issue related to the user assignment in v0.0.6 which might be causing users on older APKs to log out frequently. Does this issue still exists in v0.0.6?

**Comment by AnnieMungai** [comment]
@hamza-vd I have not experienced this. I will check with the client to see whether they are experiencing the same issue.

**Comment by AnnieMungai** [comment]
v.0.0.6debug
I believe this was fixed. Will check whether the client is still experiencing this with releases beyond 0.0.5.
