### ISSUE TITLE
QA for the preview  apk

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#85]
- [x] Functionality QA
- [x] Data migration QA

**Comment by AnnieMungai** [comment]
@tychus6 @Mstjamush update the issue to show all we are doing for this piece of work.

**Comment by AnnieMungai** [comment]
@tychus6 please update this issue.

**Comment by tychus6** [comment]
The data migration QA was conducted through the following steps:
1. Retrieving a copy database before and after migration.
2. Counting the number of tables in the database before and after migration.
3. Counting the number of records in each table in the database before and after migration.
The  results showed that all the data from the source database were migrated to the new database without any data loss
a detailed report can be found [here](https://docs.google.com/document/d/1h5ow3gQXqNAA-bBQ3rh0J-H9xVYcubrI/edit)

**Comment by AnnieMungai** [comment]
@Mstjamush @ellykits 

With the production release the following issues were fixed:
1) The growth graph is not popping up erratically anymore. 
2) HIA2 report - SAVE button - is responsive. But reports have to complete loading/syncing for it to work well. 
3) Tine taken to sync/generate reports - I will move this to a functionality issue.
