### ISSUE TITLE
Out of cathcment form- make vaccines inactive until a date is provided

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#87]
- [ ] On the out of catchment form, make the vaccines inactive before the date is provided.

**Comment by ellykits** [comment]
@AnnieMungai I understand the enhancement requested here however is it really necessary? As making the date required serves the same purpose (form cannot be submitted until date is provided)

**Comment by AnnieMungai** [comment]
@ellykits remember we are porting over old ZEIR functionalities to the new ZEIR. What's the LOE for this?

**Comment by AnnieMungai** [comment]
v.0.0.8-r3
Looks good!
