### ISSUE TITLE
Update PCV doses on Stock Module

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#9]
- [x] Update number of doses for PCV (Pneumococcal Conjugate Vaccine) from 2 to 4 doses per vial in the stock Module. 
![image](https://user-images.githubusercontent.com/58034047/100616321-fe6a7f00-3329-11eb-9554-a4c54429858f.png)

- [x] On the stock control page, the number of doses should change to reflect that each vial consists of 4 doses. For example: if there are 3 vials available. That would translate to a total of 12 doses.

- [x] On the PCV stock issued page, the number of children vaccinated is the total number of children vaccinated with this vaccine on {Date_Stock_Issued}. Estimate of number of vials used is calculated from number of children vaccinated divided by the set number of doses for that vaccine vial, rounded up to the next whole number. (See the stock module sheet on this [data dictionary](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=1075761441) - highlighted in Green  row 12 &13) - the PCV doses in a vial should reflect here.

**Comment by cafootitt** [comment]
@AnnieMungai I would list out each place where this calculation is used, so the engineer can use it as a check-list to ensure the change is reflected in each place it's used in the app. Maybe also including a test case would be helpful. For e.g. say the scenario is 6 vials on hand, so # of doses should be 24. On the stock issued form, example of 6 children vaccinated, so estimated vials issued on this date would be 2.

**Comment by AnnieMungai** [comment]
V.0.0.1R6

Looks good.
