### ISSUE TITLE
Include all details on the child registration data page

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#97]
Currently: The **registration data** page (on child detailed view) captures only the details that have been captured by the health worker. This leaves out any details that have not been captured. 
How it should work: All details on the child registration page should be included on the **registration data**page. If there are no details captured during registration, that field should show on the history page but with blank details ( see the recording below of a child detailed view on the old zeir). 
https://user-images.githubusercontent.com/58034047/111073868-8f3c2380-84f1-11eb-9726-90628eedd685.mp4

**Comment by ellykits** [comment]
@AnnieMungai  Is this what's desired? I remember for Unicef Tunisia we are only displaying recorded values.

**Comment by AnnieMungai** [comment]
> @AnnieMungai Is this what's desired? I remember for Unicef Tunisia we are only displaying recorded values.

Yes, it is what is required. Mainly so the Hw can know the details that were not entered while using Mvac.

**Comment by AnnieMungai** [comment]
v.0.0.8- preview
Looks good!
