### ISSUE TITLE
Sync issue with the preview release 0.0.7

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#98]
Users: Demo1
- [x] Sync – We noticed there could either be a possible downward or upward sync glitch.  Erasing data on the tablet is leading to loss of records. i.e they cannot be downloaded even after sync was completed. Another scenario is I cant see children registered on another tablet with the same facility even after complete sync.   Global search is not possible too.  We cant verify whether upward or downward because we haven’t got backend access yet to check if the file was uploaded. (Am yet to observe more on how it responds when loaded with more data)

- [x] First time registration of a child will crush the system. Afterward there is no problem.

**Comment by ellykits** [comment]
> * First time registration of a child will crush the system. Afterward there is no problem.

Which version of Android is in use? There is a bug with native form causing app crash when launching the form in versions 10 and higher




> * Offline functionality – First time login is possible with no problem. (e.g. Demo1).  Using the same logins in offline mode invokes an error “ no internet connection.’’  However changing the username to all small letters (demo1), login is successful. I am not sure what the technical explanation is.

Keycloak requires all usernames to be in lowercase

**Comment by AnnieMungai** [comment]
@ellykits should we then change all the usernames to small cases? We seem to have an issue with the Demo1 but not the others. 

I have look at the app and this is what I have found out:
- Demo 2 and 3 are working fine. Demo1 cannot log in (not sure what the problem is). 
- sync is happening okay for those users. 
- Advance search on the preview version is crashing the app.

**Comment by ellykits** [comment]
> * Offline functionality – First time login is possible with no problem. (e.g. Demo1).  Using the same logins in offline mode invokes an error “ no internet connection.’’  However changing the username to all small letters (demo1), login is successful. I am not sure what the technical explanation is.

Moved the above checklist item to the this new issue https://github.com/OpenSRP/opensrp-client-path-zeir/issues/105

**Comment by AnnieMungai** [comment]
v.0.0.8-n preview

Looks good!
